version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pet-accessories-backend
    restart: unless-stopped
    env_file:
      - .env  # Load variables from .env file
    environment:
      - NODE_ENV=development
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    volumes:
      - ./backend:/usr/src/app
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pet-accessories-frontend
    restart: unless-stopped
    env_file:
      - .env  # Load variables from .env file
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:5000/api
    volumes:
      - ./frontend:/usr/src/app
    networks:
      - app-network

  mongo:
    image: mongo:6.0
    container_name: pet-accessories-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
