version: '3'
services:
  backend:
    container_name: backend 
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb+srv://franklynux:admin123@testcluster.40akg.mongodb.net/pet-accessories
      - NODE_ENV=development
      - PORT=5000
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      - mongo
    volumes:
      - ./backend:/app/backend
      - node_modules_backend:/app/backend/node_modules
    networks:
      - app_network

  frontend:
    container_name: frontend 
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "3000:80"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      - backend
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/app/frontend
      - ./frontend/static:/var/www/static:ro
      - node_modules_frontend:/app/frontend/node_modules
    tmpfs:
      - /tmp
    networks:
      - app_network
    environment:
      - BACKEND_URL=http://backend:5000  
    user: nginx

  mongo:
    container_name: mongo 
    image: mongo:latest
    ports:
      - "27017:27017"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - mongo-data:/data/db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  node_modules_backend:
  node_modules_frontend:
  mongo-data: