version: '3'
services:
  backend:
    container_name: pet-accessories-backend
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb+srv://franklynux:admin123@testcluster.40akg.mongodb.net/pet-accessories
      - NODE_ENV=development
      - PORT=5000
    depends_on:
      - mongo
    volumes:
      - ./backend:/app/backend
      - node_modules_backend:/app/backend/node_modules
    networks:
      - app_network

  frontend:
    container_name: pet-accessories-frontend
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app/frontend
      - node_modules_frontend:/app/frontend/node_modules
    networks:
      - app_network

  mongo:
    container_name: pet-accessories-mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  node_modules_backend:
  node_modules_frontend:
  mongo-data: