version: '3.8'
services:
  backend:
    container_name: backend 
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb+srv://franklynux:admin123@testcluster.40akg.mongodb.net/pet-accessories
      - NODE_ENV=production
      - PORT=5000
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      - mongo
    volumes:
      - node_modules_backend:/app/backend/node_modules
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  frontend:
    container_name: frontend 
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "3000:80"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      - backend
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health.txt"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  mongo:
    container_name: mongo 
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  node_modules_backend:
  node_modules_frontend:
  mongo-data: