name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    uses: ./.github/workflows/backend-ci.yml

  frontend:
    uses: ./.github/workflows/frontend-ci.yml

  notify:
    needs: [backend, frontend]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check build status
        if: contains(needs.*.result, 'failure')
        run: exit 1